# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            http_basic: ~
            provider: our_db_provider

        api_seure:
            pattern:    ^/products
            methods:    [POST, PUT, DELETE]
            fos_oauth:  true
            stateless:  true
            anonymous:  false

        api_unsecure:
            pattern:    ^/(products|doc)
            methods:    [GET]
            security:   false

    access_control:
         - { path: ^/products, roles: [ IS_AUTHENTICATED_FULLY ] }